/* 
 * File:   problem_2.c
 * Author: Joe
 *
 * Created on August 24, 2015, 4:38 PM in Fatka
 * 
 * Project Euler Problem 2:
 * Each new term in the Fibonacci sequence is generated by adding 
 * the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not 
 * exceed four million, find the sum of the even-valued terms.
 */

#include <stdio.h>
#include <stdlib.h>

int main(int argc, char** argv) {
    
    int first = 1;
    int second = 1;
    int next = first;
    
    int sum = 0;
    
    while(1) {
        
        printf("I'm currently at %d.\n", next);
        next = first + second;
        first = second;
        second = next;
        
        if(next >= 4000000) {
            break;
        } else if(next % 2 == 0) {
            sum += next;
        } else {
            continue;
        }
        
    }
    
    printf("\nThe sum is %d.\n", sum);
    
    return (EXIT_SUCCESS);
}

